### PR TITLE
Docker Support in wlinux-setup

### PR DESCRIPTION
**Pull request by crramirez**
Hello,

I have a working version of the script, please test it. It needs polishment and better messages but it should work.

Remember you must log out and log in in WLinux after running this script. It will be included in the final messages.

Regards,
Carlos

### CODE REVIEW

**Comment by sirredbeard** [comment]
Merged into [it's own branch](https://github.com/WhitewaterFoundry/WLinux/tree/docker) for testing.

**Comment by sirredbeard** [comment]
I am going to be doing testing on this later this week. Sorry I didn't get to it last week.

**Comment by crramirez** [comment]
> I am going to be doing testing on this later this week. Sorry I didn't get to it last week.

Good, I just finished all the functionality. I will finish for tomorrow the script documentation and other polishments

**Comment by crramirez** [comment]
There are some cool messages I want to add to the script like "you need to close and reopen WLinux" something like that. I couldn't work today in the project but tomorrow I will submit the changes. The script is completely functional right now. Test it

**Comment by crramirez** [comment]
Excellent!!

**Comment by crramirez** [comment]
This change add the following:

1. Initial check if Docker for Windows is running, via executing the Windows docker client
2. Ask if the user really wants to change the root mounting point
3. Final message telling the user to exit and open WLinux again

Please check the messages I am not sure that are well written.

**Comment by crramirez** [comment]
:-D :-D :-D :-D

**Comment by sirredbeard** [comment]
We are going to let it bake for a few days, let updaters do some testing, then we will do a big announcement as part of a new build next week.

**Pull request merged**
