### PR TITLE
Beginnings of built-in Pulse Audio support

### PR DESCRIPTION
**Pull request by sirredbeard**

### CODE REVIEW

**Comment by sirredbeard** [comment]
Instead of winsw and elevate, how about: https://docs.microsoft.com/en-us/windows/desktop/taskschd/schtasks?

**Comment by sirredbeard** [comment]
Or https://github.com/troytse/wsl-autostart

**Comment by patrick330602** [comment]
Actually, I personally uses a .vbs script in startup to enable pulseaudio in Windows.... I think this is possibly the best way currently, or use a batch script.

**Comment by patrick330602** [comment]
Here is my implementation `startpulseaudio.vbe`:

```vb
set ws=wscript.createobject("wscript.shell")
ws.run "C:\WSL\scripts\pulseaudio\bin\pulseaudio.exe",0
```

**Pull request closed without merging**
