### PR TITLE
Warn if the user didn't select anything

### PR DESCRIPTION
**Pull request by crramirez**
Avoid that the user hover an option but doesn't press SPACE and then press ENTER and thinks that the option was selected, like the issue #242.

It shows a message if no option was selected

### CODE REVIEW

**Comment by grufwub** [comment]
This is a good idea :+1: will test it later

**Comment by grufwub** [comment]
Took a look and this works, though user may get a little confused if they scroll down and see the 'none' option. Or, if they unselect none, then nothing still happens.

I changed your idea a little to prompt on no-selection asking if they want to continue or not: https://github.com/grufwub/WLinux/tree/warn-no-selection

**Comment by crramirez** [comment]
Hello Kim,

In my tests I didn't see the NONE option, because it doesn't have the
label. In your tests you saw the NONE option? I didn't go trough the if [[
$CHOICE == "" ]] ; then because it destroys the Cancel button.

Regards

**Comment by grufwub** [comment]
You have to scroll down as the whiptail line count doesn't have enough space to show it by default, but the button is definitely there as described if you check this video: https://imgur.com/a/EC6pDaU

**Comment by grufwub** [comment]
Okay I fixed the broken cancel button in my [latest commit](https://github.com/grufwub/WLinux/tree/warn-no-selection). You can see how my alternative behaves here: http://sendvid.com/fjhgm7sc

**Comment by crramirez** [comment]
I will check. Thank you

**Comment by crramirez** [comment]
@grufwub Your solution is better and more elegant I recommend using it instead of mine

**Pull request merged**
