### PR TITLE
Fix pip3 path bug

### PR DESCRIPTION
**Pull request by ThatWeirdAndrew**
Fixes "/etc/setup: line 482: pip3: command not found" error during wlinux-setup

### CODE REVIEW

**Comment by sirredbeard** [comment]
You know I am still having issues getting pip3 to run after running wlinux-setup.

**Comment by OpticGenius** [comment]
After I ran `wlinux-setup`, I ran the below commands to setup `python3` and `pip3`:

`sudo apt update`
`sudo apt upgrade`
`sudo apt install python3`
`sudo apt install python3-pip`

Haven't had any noticeable issues thus far.

**Comment by ThatWeirdAndrew** [comment]
@sirredbeard I changed it so it installs pip from the debian repository. Does that  help?

**Comment by sirredbeard** [comment]
Isn't pip in Debian repo super old?

If we install from Debian repo, can we then update it to latest using 
pip?

**Comment by ThatWeirdAndrew** [comment]
According to the pip documentation, you can upgrade pip by running `pip install -U pip`. I have added this to the commit.

**Comment by ThatWeirdAndrew** [comment]
Do we want to install pip for python 2 and 3 or just 3?

**Comment by sirredbeard** [comment]
I think just 3. Your thoughts?

**Comment by ThatWeirdAndrew** [comment]
I think 3 is enough for most people. If someone needs python 2 for a specific project, they would probably know how to install it.

**Comment by sirredbeard** [comment]
Agreed.

**Comment by ThatWeirdAndrew** [comment]
The latest commit should fix the issue. Would you mind testing it to see if it fixed your problem?

**Comment by sirredbeard** [comment]
I will. Thank you.

**Pull request merged**
