### PR TITLE
Fixed: docker bg process died? #165

### PR DESCRIPTION
**Pull request by crramirez**

### CODE REVIEW

**Comment by crramirez** [comment]
Added a most robust way to test if the socket is already working correctly and weather it is working correctly in order to avoid killing a socket used by other process

**Comment by sirredbeard** [comment]
```
hayden@t470s:~$ wlinux-setup
Starting wlinux-setup.
No WSL hotfixes required.
Selected: DOCKER
DOCKER
Installing the bridge to Docker.
Saving current directory as $CURDIR
Going to $TMPDIR: /tmp/tmp.j1wsiUVBWp
--2018-11-12 15:05:11--  https://download.docker.com/linux/static/stable/x86_64/docker-18.06.1-ce.tgz
Resolving download.docker.com (download.docker.com)... 52.84.133.176, 52.84.133.21, 52.84.133.156, ...
Connecting to download.docker.com (download.docker.com)|52.84.133.176|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 43831680 (42M) [application/x-tar]
Saving to: ‘docker-18.06.1-ce.tgz’

docker-18.06.1-ce.tgz         100%[=================================================>]  41.80M  13.0MB/s    in 3.3s

2018-11-12 15:05:14 (12.8 MB/s) - ‘docker-18.06.1-ce.tgz’ saved [43831680/43831680]

[sudo] password for hayden:
docker/docker
Reading package lists...
Building dependency tree...
Reading state information...
socat is already the newest version (1.7.3.2-2).
The following packages were automatically installed and are no longer required:
  initscripts insserv startpar sysv-rc
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
%sudo   ALL=NOPASSWD: /usr/bin/docker-relay
addgroup: The group `docker' already exists.
The user `hayden' is already a member of `docker'.
Running the relay for the first time.
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:20:43 2018
 OS/Arch:           linux/amd64
 Experimental:      false
error during connect: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.38/version: EOF
Installing bash-completion
Reading package lists...
Building dependency tree...
Reading state information...
bash-completion is already the newest version (1:2.8-2).
The following packages were automatically installed and are no longer required:
  initscripts insserv startpar sysv-rc
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  104k  100  104k    0     0   579k      0 --:--:-- --:--:-- --:--:--  579k
Installing docker-compose
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   617    0   617    0     0   2603      0 --:--:-- --:--:-- --:--:--  2614
100 11.2M  100 11.2M    0     0  6757k      0  0:00:01  0:00:01 --:--:-- 11.3M
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 13034  100 13034    0     0  93100      0 --:--:-- --:--:-- --:--:-- 93100
docker-compose version 1.22.0, build f46880fe
docker-py version: 3.4.1
CPython version: 3.6.6
OpenSSL version: OpenSSL 1.1.0f  25 May 2017
Changing the root from /mnt to /
Returning to /home/hayden
Cleaning up /tmp/tmp.j1wsiUVBWp
hayden@t470s:~$ docker pull ubuntu
Using default tag: latest
Warning: failed to get default registry endpoint from daemon (error during connect: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.38/info: EOF). Using system default: https://index.docker.io/v1/
error during connect: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.38/images/create?fromImage=ubuntu&tag=latest: EOF
hayden@t470s:~$
```

**Comment by sirredbeard** [comment]
Can you please double-check the errors above aren't the result of the change?

**Comment by cicorias** [comment]
i'm not sure changing the verification if it's working will address this. It's a tmux and npiperelay "issues".  Once it dies, running `sudo docker-relay &` dies immediately as the pipe file is there.

**Comment by sirredbeard** [comment]
I know you are busy today. When you get a chance. For now I have reverted the changes. Please tweak if necessary (or tell me what I did wrong) and re-submit. Thank you.

**Comment by crramirez** [comment]
I am more free now. I made a change but is cosmetic. Try to close WLinux and execute the setup again. Indeed the unix socket and relay solution, in my opinion is not as reliable as I though, maybe in newer WSL versions the feature will be better. I would recommend every user to Expose the 2375 port without TLS, and is it is a concern use the relay solution. Both ways are implemented in the setup depending on the port is open or not.

**Comment by sirredbeard** [comment]
No problem. It happens.

It was:

```
error during connect: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.38/version: EOF
```
and
```
Warning: failed to get default registry endpoint from daemon (error during connect: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.38/info: EOF). Using system default: https://index.docker.io/v1/
error during connect: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.38/images/create?fromImage=ubuntu&tag=latest: EOF
```
That made me nervous.

If this was just a fluke, could you please re-submit #171? Thank you.

**Pull request merged**
